name: pentest
on:
  workflow_dispatch:

jobs:
  scanner:
    runs-on: [self-hosted, linux, x64, dotCMS-server]
#   timeout-minutes: 10

    steps:
      - name: Start dotCMS with docker
        run: |
          docker-compose down && docker-compose up -d
          docker ps --filter "name=dotcms" --format '{{.Names}}' | grep -q 'dotcms'

      - name: Pull latest changes for RunnerTest repository
        run: git -C /home/kali/RunnerTest pull

#     - name: Sleep until dotCMS is running
#       run: sleep 3m

      - name: Run nikto scan
        run: nikto -h localhost:8082 |& tee /home/kali/RunnerTest/report.txt

      - name: Configure Git
        run: |
          git config --global user.name "TommyB13"
          git config --global user.email "tommybennett72@gmail.com"

      - name: Add changes
        run: git -C /home/kali/RunnerTest add .

      - name: Commit changes
        run: git -C /home/kali/RunnerTest commit -m "Updated scan report"

      - name: Push updates to GitHub repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SECRET_TOKEN }}
          branch: main
          force: true
          directory: /home/kali/RunnerTest/
          repository: TommyB13/RunnerTest
